# Generated by Django 3.0.3 on 2022-01-21 11:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('scheda', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='myuser',
            name='corporation',
            field=models.CharField(blank=True, max_length=30),
        ),
        migrations.AddField(
            model_name='myuser',
            name='phone',
            field=models.CharField(blank=True, max_length=30),
        ),
    ]
