# Generated by Django 3.0.3 on 2022-01-05 08:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('scheda', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='question',
            name='example',
            field=models.IntegerField(default=7),
        ),
    ]
