# Generated by Django 3.0.3 on 2022-02-16 18:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('scheda', '0002_auto_20220216_1837'),
    ]

    operations = [
        migrations.AddField(
            model_name='scheda',
            name='frequenza',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
