# Generated by Django 3.0.3 on 2022-02-17 10:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('scheda', '0003_scheda_frequenza'),
    ]

    operations = [
        migrations.AlterField(
            model_name='scheda',
            name='emorragie',
            field=models.BooleanField(blank=True, null=True),
        ),
    ]
