# Generated by Django 3.0.3 on 2022-02-03 09:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('scheda', '0004_auto_20220203_1034'),
    ]

    operations = [
        migrations.AddField(
            model_name='mezzo',
            name='equip_min',
            field=models.IntegerField(default=None),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='mezzo',
            name='num_mezzo',
            field=models.IntegerField(default=None),
            preserve_default=False,
        ),
    ]
