# Generated by Django 3.0.3 on 2022-02-17 11:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('scheda', '0005_auto_20220217_1209'),
    ]

    operations = [
        migrations.AlterField(
            model_name='scheda',
            name='palpo',
            field=models.CharField(blank=True, max_length=10, null=True),
        ),
        migrations.AlterField(
            model_name='scheda',
            name='temperatura',
            field=models.FloatField(blank=True, null=True),
        ),
    ]
