# Generated by Django 3.0.3 on 2022-02-10 18:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('scheda', '0005_auto_20220203_1049'),
    ]

    operations = [
        migrations.AddField(
            model_name='missione',
            name='cap_intervento',
            field=models.IntegerField(default=None),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='missione',
            name='cap_residenza',
            field=models.IntegerField(default=None),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='missione',
            name='civico_intervento',
            field=models.CharField(default=None, max_length=5),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='missione',
            name='civico_residenza',
            field=models.CharField(default=None, max_length=5),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='missione',
            name='provincia_intervento',
            field=models.CharField(default=None, max_length=2),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='missione',
            name='provincia_residenza',
            field=models.CharField(default=None, max_length=2),
            preserve_default=False,
        ),
    ]
