# Generated by Django 3.0.3 on 2022-02-17 17:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('scheda', '0006_auto_20220217_1219'),
    ]

    operations = [
        migrations.AddField(
            model_name='scheda',
            name='sudore_freddo',
            field=models.BooleanField(blank=True, null=True),
        ),
    ]
