# Generated by Django 3.0.3 on 2022-02-17 21:32

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('scheda', '0007_scheda_sudore_freddo'),
    ]

    operations = [
        migrations.RenameField(
            model_name='missione',
            old_name='fine',
            new_name='accetta_missione',
        ),
        migrations.RenameField(
            model_name='missione',
            old_name='inizio',
            new_name='conferma_trasporto',
        ),
        migrations.RenameField(
            model_name='missione',
            old_name='sede',
            new_name='libero',
        ),
        migrations.AddField(
            model_name='missione',
            name='cognome_s',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
        migrations.AddField(
            model_name='missione',
            name='cognome_t',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
        migrations.AddField(
            model_name='missione',
            name='criticita_trasporto',
            field=models.CharField(blank=True, max_length=1, null=True),
        ),
        migrations.AddField(
            model_name='missione',
            name='nome_s',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
        migrations.AddField(
            model_name='missione',
            name='nome_t',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
        migrations.AddField(
            model_name='missione',
            name='ospedale',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
        migrations.AddField(
            model_name='missione',
            name='patologia_trasporto',
            field=models.CharField(blank=True, max_length=5, null=True),
        ),
        migrations.AddField(
            model_name='missione',
            name='reparto',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
        migrations.AddField(
            model_name='missione',
            name='rientro_sede',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='missione',
            name='rifiuto_trasporto',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='missione',
            name='invio',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
    ]
