# Generated by Django 3.0.3 on 2022-02-10 18:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('scheda', '0007_auto_20220210_1926'),
    ]

    operations = [
        migrations.AlterField(
            model_name='missione',
            name='invio',
            field=models.DateTimeField(auto_now_add=True),
        ),
    ]
