# Generated by Django 3.0.3 on 2022-02-10 18:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('scheda', '0008_auto_20220210_1936'),
    ]

    operations = [
        migrations.AlterField(
            model_name='missione',
            name='arrivo',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='missione',
            name='data_nascita',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='missione',
            name='fine',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='missione',
            name='inizio',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='missione',
            name='partenza',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='missione',
            name='pronto_socc',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='missione',
            name='sede',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
