# Generated by Django 3.0.3 on 2022-02-10 18:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('scheda', '0009_auto_20220210_1947'),
    ]

    operations = [
        migrations.AlterField(
            model_name='missione',
            name='cap_residenza',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='missione',
            name='cellulare',
            field=models.CharField(blank=True, max_length=15, null=True),
        ),
        migrations.AlterField(
            model_name='missione',
            name='civico_residenza',
            field=models.CharField(blank=True, max_length=5, null=True),
        ),
        migrations.AlterField(
            model_name='missione',
            name='comune_residenza',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
        migrations.AlterField(
            model_name='missione',
            name='dove_nato',
            field=models.CharField(blank=True, max_length=25, null=True),
        ),
        migrations.AlterField(
            model_name='missione',
            name='esito',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
        migrations.AlterField(
            model_name='missione',
            name='eta',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='missione',
            name='nome_p',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
        migrations.AlterField(
            model_name='missione',
            name='provincia_residenza',
            field=models.CharField(blank=True, max_length=2, null=True),
        ),
        migrations.AlterField(
            model_name='missione',
            name='residenza',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
