# Generated by Django 3.0.3 on 2022-02-11 15:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('scheda', '0010_auto_20220210_1950'),
    ]

    operations = [
        migrations.AddField(
            model_name='missione',
            name='chiusa',
            field=models.BooleanField(default=False),
        ),
    ]
