# Generated by Django 3.0.3 on 2022-02-11 15:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('scheda', '0011_missione_chiusa'),
    ]

    operations = [
        migrations.AlterField(
            model_name='scheda',
            name='allergie',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='scheda',
            name='ascolto',
            field=models.BooleanField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='scheda',
            name='avpu',
            field=models.CharField(blank=True, max_length=1, null=True),
        ),
        migrations.AlterField(
            model_name='scheda',
            name='braccia_c',
            field=models.CharField(blank=True, max_length=10, null=True),
        ),
        migrations.AlterField(
            model_name='scheda',
            name='circoloBLS',
            field=models.BooleanField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='scheda',
            name='conto',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='scheda',
            name='cosciente',
            field=models.BooleanField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='scheda',
            name='cute',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
        migrations.AlterField(
            model_name='scheda',
            name='dae',
            field=models.BooleanField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='scheda',
            name='dispnea',
            field=models.BooleanField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='scheda',
            name='dolore_toracico',
            field=models.BooleanField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='scheda',
            name='emorragie',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
        migrations.AlterField(
            model_name='scheda',
            name='farmaci',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='scheda',
            name='forza_inf',
            field=models.CharField(blank=True, max_length=10, null=True),
        ),
        migrations.AlterField(
            model_name='scheda',
            name='forza_sup',
            field=models.CharField(blank=True, max_length=10, null=True),
        ),
        migrations.AlterField(
            model_name='scheda',
            name='glicemia',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='scheda',
            name='linguaggio_c',
            field=models.BooleanField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='scheda',
            name='mimica_c',
            field=models.CharField(blank=True, max_length=10, null=True),
        ),
        migrations.AlterField(
            model_name='scheda',
            name='note',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='scheda',
            name='noteBLS',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='scheda',
            name='ora_dolore',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='scheda',
            name='osservo',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
        migrations.AlterField(
            model_name='scheda',
            name='ossigeno',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='scheda',
            name='ostruzione',
            field=models.BooleanField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='scheda',
            name='palpo',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
        migrations.AlterField(
            model_name='scheda',
            name='pasto',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='scheda',
            name='patologie',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='scheda',
            name='pervieta',
            field=models.BooleanField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='scheda',
            name='polso',
            field=models.BooleanField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='scheda',
            name='posizione',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
        migrations.AlterField(
            model_name='scheda',
            name='pressione_massima',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='scheda',
            name='pressione_minima',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='scheda',
            name='regolare_polso',
            field=models.BooleanField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='scheda',
            name='respiraBLS',
            field=models.BooleanField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='scheda',
            name='saturazione',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='scheda',
            name='saturazione_oss',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='scheda',
            name='scenario',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
        migrations.AlterField(
            model_name='scheda',
            name='sens_inf',
            field=models.CharField(blank=True, max_length=10, null=True),
        ),
        migrations.AlterField(
            model_name='scheda',
            name='sens_sup',
            field=models.CharField(blank=True, max_length=10, null=True),
        ),
        migrations.AlterField(
            model_name='scheda',
            name='spazio',
            field=models.BooleanField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='scheda',
            name='sudato',
            field=models.BooleanField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='scheda',
            name='temperatura',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='scheda',
            name='tempo',
            field=models.BooleanField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='scheda',
            name='testa_piedi_back',
            field=models.ImageField(blank=True, null=True, upload_to=''),
        ),
        migrations.AlterField(
            model_name='scheda',
            name='testa_piedi_front',
            field=models.ImageField(blank=True, null=True, upload_to=''),
        ),
        migrations.AlterField(
            model_name='scheda',
            name='tipo_dolore',
            field=models.BooleanField(blank=True, null=True),
        ),
    ]
