# Generated by Django 3.0.3 on 2022-02-18 13:31

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('scheda', '0012_auto_20220218_0116'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='missione',
            name='eta',
        ),
    ]
