# Generated by Django 3.0.3 on 2022-02-11 16:43

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('scheda', '0012_auto_20220211_1634'),
    ]

    operations = [
        migrations.AlterField(
            model_name='intervento',
            name='id_mezzo',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='scheda.Mezzo'),
        ),
        migrations.AlterField(
            model_name='intervento',
            name='id_missione',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='scheda.Missione'),
        ),
        migrations.AlterField(
            model_name='intervento',
            name='id_scheda',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='scheda.Scheda'),
        ),
    ]
