# Generated by Django 3.0.3 on 2022-02-18 15:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('scheda', '0013_remove_missione_eta'),
    ]

    operations = [
        migrations.AlterField(
            model_name='missione',
            name='ospedale',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
    ]
