# Generated by Django 3.0.3 on 2022-02-19 17:19

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('scheda', '0015_auto_20220218_1630'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='scheda',
            name='noteBLS',
        ),
    ]
