# Generated by Django 3.0.3 on 2022-02-21 19:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('scheda', '0016_remove_scheda_notebls'),
    ]

    operations = [
        migrations.AlterField(
            model_name='scheda',
            name='cicli',
            field=models.IntegerField(blank=True, default=0, null=True),
        ),
    ]
