# Generated by Django 3.0.3 on 2022-02-26 14:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('scheda', '0017_auto_20220221_2002'),
    ]

    operations = [
        migrations.AlterField(
            model_name='missione',
            name='avvisi',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='missione',
            name='cognome_p',
            field=models.CharField(blank=True, default='NON DEFINITO', max_length=20, null=True),
        ),
        migrations.AlterField(
            model_name='missione',
            name='note',
            field=models.TextField(blank=True, null=True),
        ),
    ]
