# Generated by Django 3.0.3 on 2022-02-26 14:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('scheda', '0018_auto_20220226_1553'),
    ]

    operations = [
        migrations.AlterField(
            model_name='missione',
            name='cognome_p',
            field=models.CharField(blank=True, default='NON DEFINITO', max_length=20),
        ),
    ]
