# Generated by Django 3.0.3 on 2022-02-26 14:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('scheda', '0019_auto_20220226_1556'),
    ]

    operations = [
        migrations.AlterField(
            model_name='missione',
            name='cognome_p',
            field=models.CharField(default='NON DEFINITO', max_length=20),
        ),
    ]
