# Generated by Django 3.0.3 on 2022-03-07 17:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('scheda', '0023_auto_20220226_1604'),
    ]

    operations = [
        migrations.AlterField(
            model_name='missione',
            name='esito',
            field=models.BooleanField(blank=True, null=True),
        ),
    ]
