# Generated by Django 3.0.3 on 2022-04-15 09:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('exif_viewer', '0003_auto_20220415_1132'),
    ]

    operations = [
        migrations.AlterField(
            model_name='exifimage',
            name='img',
            field=models.ImageField(blank=True, null=True, upload_to='exif/'),
        ),
    ]
