# Generated by Django 3.0.3 on 2022-04-15 09:44

import django.core.files.storage
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('exif_viewer', '0004_auto_20220415_1134'),
    ]

    operations = [
        migrations.AlterField(
            model_name='exifimage',
            name='img',
            field=models.ImageField(blank=True, null=True, storage=django.core.files.storage.FileSystemStorage(location='/home/lisa/Desktop/HCI_project/mattoni/exif_viewer/static/exif_viewer/upload/exif/'), upload_to=''),
        ),
    ]
